#!/bin/sh
set -e
if [ "$1" = configure ]
then
    update-alternatives --install /usr/bin/numba numba /usr/share/python3-numba/numba 20
fi

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-numba 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-numba  || true
fi

# End automatically added section

