#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = deconfigure ]
then
	update-alternatives --remove numba /usr/share/python3-numba/numba
fi

# Automatically added by dh_python3:
if which py3clean >/dev/null 2>&1; then
	py3clean -p python3-numba 
else
	dpkg -L python3-numba | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section

